name: Release

on:
  release:
    types: [created]

jobs:
  linux-host-publish:
    name: Release on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Release JVM, Android, JS, Linux
        run: ./gradlew publishAllFilteredToSonatype \
          -Ptarget=all_linux_hosted \
          -Psigning.key=${{ secrets.SIGNING_KEY }} \
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
      - name: Release Metadata
        run: ./gradlew publishAllFilteredToSonatype \
          -Ptarget=meta \
          -Psigning.key=${{ secrets.SIGNING_KEY }} \
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
  macos-host-publish:
    name: Release on macOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Release iOS, MacOS
        run: ./gradlew publishAllFilteredToSonatype \
          -Ptarget=all_macos_hosted \
          -Psigning.key=${{ secrets.SIGNING_KEY }} \
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }} \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
  linux-host-check:
    name: Check on Ubuntu
    runs-on: ubuntu-latest
    needs: linux-host-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Check JVM, Android, JS, Linux
        run: ./gradlew :tools:check-publication:build \
          -Ptarget=all_linux_hosted \
          -Pcheck_publication \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
  macos-host-check:
    name: Check on macOS
    runs-on: macOS-latest
    needs: [linux-host-publish, macos-host-publish]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check iOS
        run: ./gradlew :tools:check-publication:build \
          -Ptarget=all_macos_hosted \
          -Pcheck_publication \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password=${{ secrets.SONATYPE_PASSWORD }}
